version: '3.11'

services:
  emarketdb:
    restart: always
    image: postgres
    container_name: emarketdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
  web:
    build: .
    container_name: emarketweb
    command: /bin/sh /emarket/startdjango.sh
    volumes:
      - ./emarketdb_dump.json:/emarket/emarketdb_dump.json
      - ./emarket/media:/emarket-statics/uploads
    expose:
      - 80
    depends_on:
      - emarketdb
    env_file:
      - .env
  nginx:
    container_name: emarketnginx
    build: ./nginx
    volumes:
      - ./emarket/static:/emarket-statics/static
      - ./emarket/media:/emarket-statics/uploads
      - /etc/letsencrypt/live/xn----8sbncyk3as.xn--p1ai/fullchain.pem:/etc/letsencrypt/live/xn----8sbncyk3as.xn--p1a>
      - /etc/letsencrypt/live/xn----8sbncyk3as.xn--p1ai/privkey.pem:/etc/letsencrypt/live/xn----8sbncyk3as.xn--p1ai/>
    ports:
      - "443:443"
    depends_on:
      - web

volumes:
  postgres_data: