version: '3.11'

services:
  emarketdb:
    restart: always
    image: postgres
    container_name: emarketdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
  cache:
    image: redis
    container_name: emarketcache
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ../backups/redis.log:/var/log/redis/redis.log
    expose:
      - 6379
    command: redis-server /usr/local/etc/redis/redis.conf --bind redis-container-name
  web:
    build: .
    container_name: emarketweb
    command: /bin/sh /emarket/startdjango.sh
    volumes:
      - ./emarketdb_dump.json:/emarket/emarketdb_dump.json
      - ./emarket/media:/emarket-statics/uploads
    expose:
      - 80
    depends_on:
      - emarketdb
      - cache
    env_file:
      - .env
  nginx:
    container_name: emarketnginx
    build: ./nginx
    volumes:
      - ./emarket/static:/emarket-statics/static
      - ./emarket/media:/emarket-statics/uploads
      - /etc/letsencrypt/live/xn----8sbncyk3as.xn--p1ai/fullchain.pem:/etc/letsencrypt/live/xn----8sbncyk3as.xn--p1ai/fullchain.pem
      - /etc/letsencrypt/live/xn----8sbncyk3as.xn--p1ai/privkey.pem:/etc/letsencrypt/live/xn----8sbncyk3as.xn--p1ai/privkey.pem
      - ../backups/nginxaccesslog.log:/var/log/nginx/access.log
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data: