version: '3.11'

services:
  lunemarketdb:
    restart: always
    image: postgres
    container_name: lunemarketdb
    volumes:
      - ~/.pg/pg_data/lunemarketdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
  web:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: web
    command: python lunemarket/lunemarket/manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/lunemarket/static
      - media_volume:/lunemarket/media
    ports:
      - "8000:8000"
    depends_on:
      - lunemarketdb
    env_file:
      - .env

volumes:
  static_volume:
  media_volume:
