version: '3.11'

services:
  emarketdb:
    restart: always
    image: postgres
    container_name: emarketdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
  web:
    build: .
    container_name: web
    command: /bin/sh /emarket/startdjango.sh
    volumes:
      - static_volume:/emarket/emarket/static
      - media_volume:/emarket/emarket/media
    ports:
      - "8000:8000"
    depends_on:
      - emarketdb
    env_file:
      - .env

volumes:
  static_volume:
  media_volume:
  postgres_data:
