version: '3.11'

services:
  emarketdb:
    restart: always
    image: postgres
    container_name: emarketdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
  web:
    build: .
    container_name: web
    command: /bin/sh /emarket/startdjango.sh
    volumes:
      - ./emarketdb_dump.json:/emarket/emarketdb_dump.json
    expose:
      - 8000
    depends_on:
      - emarketdb
    env_file:
      - .env
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./emarket/static:/emarket-statics/static
      - ./emarket/media:/emarket-statics/uploads
    ports:
      - "8000:80"
    depends_on:
      - web

volumes:
  postgres_data: