name: Django

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PYTHON-VERSION: 3.11

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python $PYTHON-VERSION
      uses: actions/setup-python@v3
      with:
        python-version: $PYTHON-VERSION
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python ./emarket/manage.py test --settings=emarket.testsettings
