name: Django

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_TEST_PASSWORD }}
      POSTGRES_DB: "emarketdb"
      POSTGRES_USER: "runner"
      POSTGRES_PORT: 5432

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.0
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.0
    - name: Start PostgreSQL
      run: |
        sudo systemctl start postgresql.service
        sudo -u postgres createuser -s runner
        sudo -u postgres psql -c 'create database emarketdb;'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Preparation
      run: |
        cd ./emarket
        python manage.py migrate --noinput --settings=emarket.testsettings
        python manage.py makemigrations products --noinput --setting=emarket.testsettings
        python manage.py migrate products --noinput --settings=emarket.testsettings
        python manage.py makemigrations users --noinput --setting=emarket.testsettings
        python manage.py migrate users --noinput --settings=emarket.testsettings
        python manage.py makemigrations purchasing --noinput --setting=emarket.testsettings
        python manage.py migrate purchasing --noinput --settings=emarket.testsettings
    - name: Run Tests
      run: |
        cd ./emarket
        python manage.py test --settings=emarket.testsettings